import { ArrowRight, CheckCircle2, FileCheck2, LockKeyhole, Sparkles, UploadCloud, Zap } from "lucide-react";
import Link from "next/link";
import { ConverterWorkspace } from "@/components/converter/converter-workspace";
import { RecentConversions } from "@/components/home/recent-conversions";
import { ToolSearch } from "@/components/home/tool-search";
import { ToolCard } from "@/components/tools/tool-card";
import { categories, tools } from "@/config/tools";

const categoryIds: Record<string, string> = { "PDF Converter": "pdf-converter", "Image Converter": "image-converter", "Office Converter": "office-converter", "PDF Tools": "pdf-tools" };
export function HomeContent() { return <>
  <section className="hero-grid overflow-hidden"><div className="container-shell relative py-16 text-center sm:py-24"><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><span className="eyebrow-pill"><Sparkles size={14} /> 24 powerful conversion tools</span><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-black leading-[1.05] tracking-[-.055em] sm:text-6xl lg:text-7xl">Convert any file.<br/><span className="gradient-text">No friction. No fuss.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-muted sm:text-lg">Fast, secure and free online file converter. Convert PDF, Word, images and more with a simple three-step workflow.</p><div id="converter" className="relative mx-auto mt-10 max-w-3xl text-left"><ConverterWorkspace universal compact /></div><div className="mt-8 flex flex-wrap justify-center gap-x-6 gap-y-3 text-xs font-semibold text-muted"><span className="flex items-center gap-2"><LockKeyhole size={15} className="text-emerald-500" /> Private temporary processing</span><span className="flex items-center gap-2"><Zap size={15} className="text-amber-500" /> No paid converter API</span><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-brand" /> Up to 100 MB</span></div></div></section>
  <section className="container-shell mt-20 text-center"><p className="eyebrow">Find your tool</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">One search. Every conversion.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted">Try “JPG”, “PDF”, or the format you want to work with.</p><div className="mt-8"><ToolSearch /></div></section>
  <section id="all-tools" className="container-shell mt-24 space-y-20">{categories.map((category) => { const list = tools.filter((tool) => tool.category === category); return <div id={categoryIds[category]} className="scroll-mt-28" key={category}><div className="mb-7 flex items-end justify-between gap-4"><div><p className="eyebrow">FonixsPDF toolkit</p><h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{category}</h2></div><span className="hidden text-sm text-muted sm:block">{list.length} tools</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{list.map((tool) => <ToolCard tool={tool} key={tool.id} />)}</div></div>; })}</section>
  <section className="container-shell mt-24"><div className="rounded-[2rem] border bg-card p-7 sm:p-10"><div className="text-center"><p className="eyebrow">Simple by design</p><h2 className="mt-2 text-3xl font-black">Upload. Convert. Download.</h2></div><div className="mt-10 grid gap-7 md:grid-cols-3">{[[UploadCloud, "01", "Upload your file", "Drag, drop, or choose a supported file up to 100 MB."], [Sparkles, "02", "We convert it", "Open-source engines process your file in temporary storage."], [FileCheck2, "03", "Download the result", "Get your converted file. Server copies expire automatically."]].map(([Icon, number, title, body]) => { const StepIcon = Icon as typeof UploadCloud; return <div key={String(number)} className="relative rounded-2xl bg-soft p-6"><span className="absolute right-5 top-5 text-xs font-black text-brand">{String(number)}</span><span className="section-icon"><StepIcon /></span><h3 className="mt-5 font-extrabold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-muted">{String(body)}</p></div>; })}</div></div></section>
  <section className="container-shell mt-20 grid gap-5 md:grid-cols-3">{[[LockKeyhole, "Secure by default", "Random internal filenames, strict format checks, and automatic cleanup."], [Zap, "Runs locally", "No paid converter API and no account required for conversions."], [CheckCircle2, "Built for every screen", "A clean experience from desktop browsers to mobile devices."]].map(([Icon, title, body]) => { const ItemIcon = Icon as typeof LockKeyhole; return <div className="flex gap-4 rounded-2xl border bg-card p-5" key={String(title)}><ItemIcon className="shrink-0 text-brand"/><div><h3 className="font-bold">{String(title)}</h3><p className="mt-1 text-sm leading-6 text-muted">{String(body)}</p></div></div>; })}</section>
  <RecentConversions />
  <section className="container-shell mt-24"><div className="cta-panel"><div><p className="eyebrow text-cyan-200">Fast. Simple. Free.</p><h2 className="mt-2 text-3xl font-black text-white">Ready to convert your next file?</h2><p className="mt-3 text-sm text-slate-300">Choose from all available PDF, image, and Office tools.</p></div><Link href="#all-tools" className="primary-button bg-white text-slate-950 hover:bg-cyan-50">Explore all tools <ArrowRight size={18}/></Link></div></section>
  </>; }
